---
title: "puert-2-rico"
author: "Jessica French"
date: "2022-08-24"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE)
```

```{r}
library(tidyverse)
library(lubridate)
library(janitor)
library(patchwork)
library(ggpubr)
library(paletteer)
library(ggExtra)
library(here)

```

## Read in data files in csv format 
```{r}
bq1 <- read_csv(file.path("","courses", "EDS214", "puert-2-rico", "raw_data", "QuebradaCuenca1-Bisley.csv"))
bq2 <- read_csv(file.path("","courses", "EDS214", "puert-2-rico", "raw_data", "QuebradaCuenca2-Bisley.csv"))
bq3 <- read_csv(file.path("","courses", "EDS214", "puert-2-rico", "raw_data", "QuebradaCuenca3-Bisley.csv"))
prm <- read_csv(file.path("","courses", "EDS214", "puert-2-rico", "raw_data", "RioMameyesPuenteRoto.csv"))
```


```{r}

columns_vector <- c("Sample_ID", "Sample_Date", "NO3-N", "K") #vector of columns to be kept. 


#select columns form columns vector, create columns for month and year and filter to rows that contain years 1988 to 1994. 
bq1_tidy <- bq1 |> 
  select(columns_vector) |> #---- subset to include only the columns (variables) we want
  mutate(Year = year(Sample_Date), Month = month(Sample_Date)) |>   #---- add a new column with year - month combination
  filter(Year %in% c(seq(from = 1988, to = 1994))) #---- subset only for rows in the time frame of interest

bq2_tidy <- bq2 |>   #---- complete the exact same steps for the following three data sets 
  select(columns_vector) |>      
  mutate(Year = year(Sample_Date), Month = month(Sample_Date)) |> 
  filter(Year %in% c(seq(from = 1988, to = 1994)))

bq3_tidy <- bq3 |> 
  select(columns_vector) |> 
  mutate(Year = year(Sample_Date), Month = month(Sample_Date)) |> 
  filter(Year %in% c(seq(from = 1988, to = 1994)))

prm_tidy <- prm |> 
  select(columns_vector) |> 
  mutate(Year = year(Sample_Date), Month = month(Sample_Date)) |> 
  filter(Year %in% c(seq(from = 1988, to = 1994)))

#Combine four data sets into one data frame. 
combined_data <- bind_rows(bq1_tidy, bq2_tidy, bq3_tidy, prm_tidy)

```

```{r}
#Create one column of month and year in date format so that nitrogen concentration can be summarized by month and year.

date_column_only <- combined_data |> 
  select(Sample_Date, Sample_ID)

combined_data_mean <- combined_data |> 
  mutate(Month_Year = paste(month(Sample_Date), year(Sample_Date))) |> 
  mutate(Month_Year = my(Month_Year)) |> 
  group_by(Month_Year, Sample_ID) |> 
  summarize(Monthly_Mean_N = mean(`NO3-N`, na.rm = TRUE), 
            Monthly_Mean_K = mean(K, na.rm = TRUE)) 

```


```{r}
#Expression for nitrogen axis title
n_axis_title <- expression('Mean NO'[3]*'-N '*mu*'g -1 L')

# Plot of mean monthly nitrogen concentration from 1988 to 1994. 
plot_1989_1994_N <- ggplot(data = combined_data_mean, 
                           aes(x = Month_Year,
                               y = Monthly_Mean_N)) +
  geom_line(aes(linetype = Sample_ID, 
                color = Sample_ID)) +
  labs(x = "Year",
       y =  n_axis_title) +
  scale_color_paletteer_d("fishualize::Koumansetta_rainfordi") +
  guides(color = guide_legend(title = "Sample Site"), 
         linetype = guide_legend(title = "Sample Site")) +
  theme_minimal() +
  geom_vline(xintercept = ymd("1989-09-01"), 
             linetype = "solid")
  

plot_1989_1994_N
```


```{r}

# Plot of mean monthly potassium concentration from 1988 to 1994. 
plot_1989_1994_K <- ggplot(data = combined_data_mean, 
                           aes(x = Month_Year,
                               y = Monthly_Mean_K)) +
  geom_line(aes(linetype = Sample_ID, 
                color = Sample_ID)) +
  labs(x = "Year",
       y = "Mean K mg -1 L") +
  scale_color_paletteer_d("fishualize::Koumansetta_rainfordi") +
  guides(color = guide_legend(title = "Sample Site"), 
         linetype = guide_legend(title = "Sample Site")) +
  theme_minimal() +
  geom_vline(xintercept = ymd("1989-09-01"), linetype = "solid") +
  annotate("text", 
           x = ymd("1991-01-01"), 
           y = 1.8, 
           label = "Hurrican Hugo", 
           color = "black", 
           size = 3) 
 


plot_1989_1994_K
```

```{r}


bq1_clean <- bq1 %>% select(Sample_ID, Sample_Date, K, `NO3-N`) %>% 
  mutate(Year = lubridate::year(Sample_Date)) %>% 
  filter(Year %in% c(2011,2012,2013,2014,2015,2016,2017,2018))

bq2_clean <- bq2 %>% select(Sample_ID, Sample_Date, K, `NO3-N`) %>% 
  mutate(Year = lubridate::year(Sample_Date)) %>% 
  filter(Year %in% c(2011,2012,2013,2014,2015,2016,2017,2018))

bq3_clean <- bq3 %>% select(Sample_ID, Sample_Date, K, `NO3-N`) %>% 
  mutate(Year = lubridate::year(Sample_Date)) %>% 
  filter(Year %in% c(2011,2012,2013,2014,2015,2016,2017,2018))

prm_clean <- prm %>% select(Sample_ID, Sample_Date, K, `NO3-N`) %>% 
  mutate(Year = lubridate::year(Sample_Date)) %>% 
  filter(Year %in% c(2011,2012,2013,2014,2015,2016,2017,2018))
```

```{r}
q2_allsites_K <- bind_rows(bq1_clean, bq2_clean, bq3_clean, prm_clean) %>% 
  mutate(Month_Year = paste(lubridate::month(Sample_Date),lubridate::year(Sample_Date))) %>% 
  mutate(Month_Year = lubridate:: my(Month_Year)) %>% 
  group_by(Month_Year, Sample_ID) %>% summarise(mean = mean(K))

plot_2014_2018_K <- ggplot(q2_allsites_K, 
                           aes(x = Month_Year, 
                               y = mean)) + 
  geom_line(aes(linetype = Sample_ID,
                color = Sample_ID)) + scale_color_paletteer_d("fishualize::Koumansetta_rainfordi") + 
  labs(x = "Year",
       y = "Mean K mg -1 L") +
  guides(color = guide_legend(title = "Sample Site"), 
         linetype = guide_legend(title = "Sample Site")) +
  geom_vline(xintercept = ymd("2017-09-01"), linetype = "solid") +
  annotate("text", 
           x = ymd("2016-05-01"), 
           y = 1.4, 
           label = "Hurrican Maria", 
           color = "black", 
           size = 3) +
  theme_minimal()

plot_2014_2018_K
```

```{r}
q1_allsites_NO3 <- bind_rows(bq1_clean, bq2_clean, bq3_clean, prm_clean) %>% 
  mutate(Month_Year = paste(lubridate::month(Sample_Date),lubridate::year(Sample_Date))) %>% 
  mutate(Month_Year = lubridate:: my(Month_Year)) %>% 
  group_by(Month_Year, Sample_ID) %>% summarise(mean = mean(`NO3-N`))

plot_2014_2018_N <- ggplot(q1_allsites_NO3, aes(x = Month_Year, 
                            y = mean)) + 
  geom_line(aes(linetype = Sample_ID,
                color = Sample_ID)) + scale_color_paletteer_d("fishualize::Koumansetta_rainfordi")  + 
  labs(x = "Year",
       y = n_axis_title) +
  guides(color = guide_legend(title = "Sample Site"), 
         linetype = guide_legend(title = "Sample Site")) + 
  geom_vline(xintercept = ymd("2017-09-01"), linetype = "solid") +
  theme_minimal()
  

plot_2014_2018_N
```



```{r}
#Combined graphs 88-94
combined_plot_88_94 <- ggarrange( 
          plot_1989_1994_K + 
               theme(axis.text.x = element_blank(),
                     axis.ticks.x = element_blank(),
                     axis.title.x = element_blank(),
                     axis.title.y = element_text(size = 9),
                     axis.text.y = element_text(size = 7)), 
          plot_1989_1994_N +
            theme(axis.title.y = element_text(size = 9),
                  axis.text.y = element_text(size = 7)),
          nrow = 2,
          ncol = 1,
          common.legend = TRUE,
          legend = "right") 

#annotate_figure_88_94 <- annotate_figure(combined_plot_88_94, top = "Mean Monthly Nitrate Levels in Watersheds in the Luquillo Experimental Forest", top = "Before and After Hurricane Maria") 

title_88_94 <- expression(atop(bold("Mean Monthly Nitrate and Potassium Concentrations"), scriptstyle("in Watersheds in the Luquillo Experimental Forest Before and After Hurricane Hugo")))

annotated_figure_88_94 <- annotate_figure(combined_plot_88_94 ,
                top=text_grob(title_88_94))
annotated_figure_88_94

ggsave("combined_88_94_plots.png", path = here('figs'))
```

```{r}
#Combined plots for 2014 to 2018
combined_plot_14_18 <- ggarrange( 
          plot_2014_2018_K + 
               theme(axis.text.x = element_blank(),
                     axis.ticks.x = element_blank(),
                     axis.title.x = element_blank(),
                     axis.title.y = element_text(size = 9),
                     axis.text.y = element_text(size = 7)),
          plot_2014_2018_N +
            theme(axis.title.y = element_text(size = 9),
                  axis.text.y = element_text(size = 7)), 
          nrow = 2,
          ncol = 1,
          common.legend = TRUE,
          legend = "right")

#annotate_figure_88_94 <- annotate_figure(combined_plot_88_94, top = "Mean Monthly Nitrate Levels in Watersheds in the Luquillo Experimental Forest", top = "Before and After Hurricane Maria") 

title_14_18 <- expression(atop(bold("Mean Monthly Nitrate and Potassium Concentrations"), scriptstyle("in Watersheds in the Luquillo Experimental Forest Before and After Hurricane Maria")))

annotated_figure_14_18 <- annotate_figure(combined_plot_14_18,
                top=text_grob(title_14_18))
annotated_figure_14_18

ggsave("combined_14_18_plots.png", path = here("figs"))
```

